# Generated by Django 3.2.9 on 2022-01-19 01:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='imageQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordSelection', models.CharField(max_length=50)),
                ('wordAttempt', models.CharField(max_length=50)),
                ('correct', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='mazeQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordSelection', models.CharField(max_length=50)),
                ('wordAttempt', models.CharField(max_length=50)),
                ('correct', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='mazeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testAdmin', models.CharField(default='null', max_length=50)),
                ('examinee', models.CharField(default='null', max_length=50)),
                ('gradeLevel', models.CharField(default='null', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mazeQuestionAttempts', models.ManyToManyField(related_name='mazeQuestionAttemps', to='dibels_test.mazeQuestionAttempt')),
                ('user', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='userMaze', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mazequestionattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dibels_test.sentence'),
        ),
        migrations.CreateModel(
            name='imageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testAdmin', models.CharField(default='null', max_length=50)),
                ('examinee', models.CharField(default='null', max_length=50)),
                ('gradeLevel', models.CharField(default='null', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('imageQuestionAttempts', models.ManyToManyField(related_name='imageQuestionAttemps', to='dibels_test.imageQuestionAttempt')),
                ('user', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='userImage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
