# Generated by Django 3.2.9 on 2022-01-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0002_auto_20220114_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='examinee',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagetest',
            name='testAdmin',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='mazetest',
            name='examinee',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='mazetest',
            name='testAdmin',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
