# Generated by Django 3.2.9 on 2022-01-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0005_auto_20220119_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetest',
            name='examinee',
        ),
        migrations.RemoveField(
            model_name='mazetest',
            name='examinee',
        ),
    ]
