# Generated by Django 3.2.9 on 2022-02-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0006_auto_20220124_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='gradeLevel',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
