# Generated by Django 3.2.9 on 2022-02-02 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0007_sentence_gradelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazetest',
            name='mazeQuestionAttemptQueue',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dibels_test.sentence'),
        ),
    ]
