# Generated by Django 3.2.9 on 2022-02-02 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0008_mazetest_mazequestionattemptqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mazetest',
            name='mazeQuestionAttemptQueue',
            field=models.ForeignKey(default='630', on_delete=django.db.models.deletion.CASCADE, to='dibels_test.sentence'),
        ),
    ]
