# Generated by Django 3.2.9 on 2022-02-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0009_alter_mazetest_mazequestionattemptqueue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mazetest',
            name='mazeQuestionAttemptQueue',
        ),
    ]
