# Generated by Django 3.2.9 on 2022-02-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0010_remove_mazetest_mazequestionattemptqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazetest',
            name='queuedGeneratedWord1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mazetest',
            name='queuedGeneratedWord2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mazetest',
            name='queuedSentenceId',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='mazetest',
            name='queuedWordSelection',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
