# Generated by Django 3.2.9 on 2022-03-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0013_auto_20220221_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('style', models.CharField(max_length=75)),
                ('angular', models.FloatField(blank=True)),
                ('artistic', models.FloatField(blank=True)),
                ('attention_grabbing', models.FloatField(blank=True)),
                ('attractive', models.FloatField(blank=True)),
                ('bad', models.FloatField(blank=True)),
                ('boring', models.FloatField(blank=True)),
                ('calm', models.FloatField(blank=True)),
                ('capitals', models.FloatField(blank=True)),
                ('charming', models.FloatField(blank=True)),
                ('clumsy', models.FloatField(blank=True)),
                ('complex', models.FloatField(blank=True)),
                ('cursive', models.FloatField(blank=True)),
                ('delicate', models.FloatField(blank=True)),
                ('disorderly', models.FloatField(blank=True)),
                ('display', models.FloatField(blank=True)),
                ('dramatic', models.FloatField(blank=True)),
                ('formal', models.FloatField(blank=True)),
                ('fresh', models.FloatField(blank=True)),
                ('friendly', models.FloatField(blank=True)),
                ('gentle', models.FloatField(blank=True)),
                ('graceful', models.FloatField(blank=True)),
                ('happy', models.FloatField(blank=True)),
                ('italic', models.FloatField(blank=True)),
                ('legible', models.FloatField(blank=True)),
                ('modern', models.FloatField(blank=True)),
                ('monospace', models.FloatField(blank=True)),
                ('playful', models.FloatField(blank=True)),
                ('pretentious', models.FloatField(blank=True)),
                ('serif', models.FloatField(blank=True)),
                ('sharp', models.FloatField(blank=True)),
                ('sloppy', models.FloatField(blank=True)),
                ('soft', models.FloatField(blank=True)),
                ('strong', models.FloatField(blank=True)),
                ('technical', models.FloatField(blank=True)),
                ('thin', models.FloatField(blank=True)),
                ('warm', models.FloatField(blank=True)),
                ('wide', models.FloatField(blank=True)),
            ],
        ),
    ]
