# Generated by Django 3.2.9 on 2022-03-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0014_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazequestionattempt',
            name='font',
            field=models.ForeignKey(default=230, on_delete=django.db.models.deletion.CASCADE, to='dibels_test.font'),
        ),
    ]
