# Generated by Django 3.2.9 on 2022-03-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0015_mazequestionattempt_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmazequestion',
            name='link',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='queuedmazequestion',
            name='style',
            field=models.CharField(default='null', max_length=75),
        ),
        migrations.AlterField(
            model_name='font',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
