# Generated by Django 3.2.9 on 2022-03-03 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0016_auto_20220303_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuedmazequestion',
            name='link',
        ),
        migrations.RemoveField(
            model_name='queuedmazequestion',
            name='style',
        ),
        migrations.AddField(
            model_name='queuedmazequestion',
            name='font',
            field=models.ForeignKey(default=230, on_delete=django.db.models.deletion.CASCADE, to='dibels_test.font'),
        ),
    ]
