# Generated by Django 4.0.3 on 2022-03-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0017_auto_20220303_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='distractorWord1',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='distractorWord2',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='selectedWord',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
