# Generated by Django 4.0.3 on 2022-03-26 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0018_sentence_distractorword1_sentence_distractorword2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedmazequestion',
            name='font',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dibels_test.font'),
        ),
    ]
