# Generated by Django 4.0.3 on 2022-03-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0022_imagequestionattempt_font_queuedimagequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=30)),
                ('gradeLevel', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
