# Generated by Django 4.0.3 on 2022-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='size',
            field=models.CharField(default='font-size: 1rem;', max_length=20),
            preserve_default=False,
        ),
    ]
